apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-flow-lab
  namespace: git-flow-lab
spec:
  ingressClassName: nginx
  rules:
    - host: git-flow-lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: git-flow-lab
                port:
                  number: 80
